// TODO: When releasing this to DefinitelyTyped, replace the following line with
// "Type definitions for XXX". Then delete this comment.
// -----------------------------------------------------------------------------
// vhtml 2.2.0 type definitions
// Project: https://github.com/developit/vhtml
// Definitions by: Yehyoung Kang <https://github.com/pastelmind/>

export = vhtml;

/**
 * Converts Hyperscript/JSX to a plain string.
 * @param name Element name
 * @param attrs Attributes
 * @param children Child elements
 */
declare function vhtml<T extends keyof JSX.IntrinsicElements>(
  name: T,
  attrs?: JSX.IntrinsicElements[T] | null,
  ...children: any[]
): string;

/**
 * Converts Hyperscript/JSX to a plain string.
 * @param component Functional pseudo-component
 * @param attrs Attributes
 * @param children Child elements
 */
declare function vhtml<Props extends VhtmlAttributes>(
  component: (props: Props) => string,
  attrs?: Props | null,
  ...children: any[]
): string;

/**
 * Converts Hyperscript/JSX to a plain string.
 * @param name Element name
 * @param attrs Attributes
 * @param children Child elements
 */
declare function vhtml(
  name: string,
  attrs?: (VhtmlAttributes & { [prop: string]: string }) | null,
  ...children: any[]
): string;

interface VhtmlAttributes {
  children?: any[];
  dangerouslySetInnerHTML?: { __html: string };
  [attr: string]: any;
}

// The following interfaces were generated by transforming large sections of
// JSX type definitions in @types/react 17.0.0. Those type definitions were
// produced by multiple contributors, including, but not limited to:
//
//                 AssureSign <http://www.assuresign.com>
//                 Microsoft <https://microsoft.com>
//                 John Reilly <https://github.com/johnnyreilly>
//                 Benoit Benezech <https://github.com/bbenezech>
//                 Patricio Zavolinsky <https://github.com/pzavolinsky>
//                 Digiguru <https://github.com/digiguru>
//                 Eric Anderson <https://github.com/ericanderson>
//                 Dovydas Navickas <https://github.com/DovydasNavickas>
//                 Josh Rutherford <https://github.com/theruther4d>
//                 Guilherme Hübner <https://github.com/guilhermehubner>
//                 Ferdy Budhidharma <https://github.com/ferdaber>
//                 Johann Rakotoharisoa <https://github.com/jrakotoharisoa>
//                 Olivier Pascal <https://github.com/pascaloliv>
//                 Martin Hochel <https://github.com/hotell>
//                 Frank Li <https://github.com/franklixuefei>
//                 Jessica Franco <https://github.com/Jessidhia>
//                 Saransh Kataria <https://github.com/saranshkataria>
//                 Kanitkorn Sujautra <https://github.com/lukyth>
//                 Sebastian Silbermann <https://github.com/eps1lon>
//                 Kyle Scully <https://github.com/zieka>
//                 Cong Zhang <https://github.com/dancerphil>
//                 Dimitri Mitropoulos <https://github.com/dimitropoulos>
//                 JongChan Choi <https://github.com/disjukr>
//                 Victor Magalhães <https://github.com/vhfmag>
//                 Dale Tan <https://github.com/hellatan>
//
// See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts
// for the up-to-date list of contributors to @types/react
